"""Add context_summary to chat_sessions

Revision ID: 22632bd3fd91
Revises: 'b0ef8cf0f7ab'
Create Date: 2026-07-31 00:54:05.527126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22632bd3fd91'
down_revision: Union[str, None] = 'b0ef8cf0f7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('context_summary', sa.JSON(), nullable=True))
    op.add_column('chat_sessions', sa.Column('is_ready_to_generate', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_ready_to_generate')
    op.drop_column('chat_sessions', 'context_summary')
    # ### end Alembic commands ###
