"""Initial tables

Revision ID: b0ef8cf0f7ab
Revises: 'None'
Create Date: 2026-07-31 00:42:26.103127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ef8cf0f7ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_artworks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('movement_style', sa.String(), nullable=True),
    sa.Column('medium', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_attribution', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('dominant_color', sa.String(), nullable=True),
    sa.Column('is_public_domain', sa.Boolean(), nullable=False),
    sa.Column('is_custom_upload', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_artworks_artist'), 'reference_artworks', ['artist'], unique=False)
    op.create_index(op.f('ix_reference_artworks_movement_style'), 'reference_artworks', ['movement_style'], unique=False)
    op.create_index(op.f('ix_reference_artworks_title'), 'reference_artworks', ['title'], unique=False)
    op.create_table('generated_artworks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('prompt_synthesized', sa.Text(), nullable=False),
    sa.Column('inspiration_level', sa.Enum('LOOSE', 'BALANCED', 'NEAR', name='inspirationlevel'), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('model_provider', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('sender', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagesender'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_references',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('reference_artwork_id', sa.String(), nullable=True),
    sa.Column('custom_image_url', sa.String(), nullable=True),
    sa.Column('is_custom_upload', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reference_artwork_id'], ['reference_artworks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('critiques',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('generated_artwork_id', sa.String(), nullable=False),
    sa.Column('summary_content', sa.Text(), nullable=False),
    sa.Column('composition_analysis', sa.Text(), nullable=False),
    sa.Column('color_theory_analysis', sa.Text(), nullable=False),
    sa.Column('symbolism_analysis', sa.Text(), nullable=True),
    sa.Column('emotional_impact_analysis', sa.Text(), nullable=False),
    sa.Column('comparison_analysis', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_artwork_id'], ['generated_artworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_artwork_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('critiques')
    op.drop_table('session_references')
    op.drop_table('messages')
    op.drop_table('generated_artworks')
    op.drop_index(op.f('ix_reference_artworks_title'), table_name='reference_artworks')
    op.drop_index(op.f('ix_reference_artworks_movement_style'), table_name='reference_artworks')
    op.drop_index(op.f('ix_reference_artworks_artist'), table_name='reference_artworks')
    op.drop_table('reference_artworks')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
