"""Add is_saved and saved_at to chat_sessions

Revision ID: c5b90266e60b
Revises: '8cfa92d86c40'
Create Date: 2026-07-31 01:24:09.818959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b90266e60b'
down_revision: Union[str, None] = '8cfa92d86c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chat_sessions', sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'saved_at')
    op.drop_column('chat_sessions', 'is_saved')
    # ### end Alembic commands ###
