"""add visual_analysis to reference_artworks

Revision ID: 7572b4aa47ee
Revises: 'c5b90266e60b'
Create Date: 2026-08-02 22:09:33.004334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7572b4aa47ee'
down_revision: Union[str, None] = 'c5b90266e60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_artworks', sa.Column('visual_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_artworks', 'visual_analysis')
    # ### end Alembic commands ###
