"""Add generation_index to generated_artworks; add structured critique fields

Revision ID: 8cfa92d86c40
Revises: '22632bd3fd91'
Create Date: 2026-07-31 01:13:10.194410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cfa92d86c40'
down_revision: Union[str, None] = '22632bd3fd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('critiques', sa.Column('reference_critique', sa.JSON(), nullable=True))
    op.add_column('critiques', sa.Column('generated_critique', sa.JSON(), nullable=True))
    op.add_column('critiques', sa.Column('comparison', sa.Text(), nullable=True))
    op.alter_column('critiques', 'summary_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('critiques', 'composition_analysis',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('critiques', 'color_theory_analysis',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('critiques', 'emotional_impact_analysis',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('critiques', 'comparison_analysis',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('generated_artworks', sa.Column('generation_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_artworks', 'generation_index')
    op.alter_column('critiques', 'comparison_analysis',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('critiques', 'emotional_impact_analysis',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('critiques', 'color_theory_analysis',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('critiques', 'composition_analysis',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('critiques', 'summary_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('critiques', 'comparison')
    op.drop_column('critiques', 'generated_critique')
    op.drop_column('critiques', 'reference_critique')
    # ### end Alembic commands ###
